### ISSUE TITLE
Issue with Running Audio File

### ISSUE THREAD

**Issue by shantanudev** [aalto-speech/speaker-diarization#1]
Hi,
I was wondering if you could help me. I am trying to run an mp3 file, but I get this error. 
Traceback (most recent call last):
  File "./spk-diarization.py", line 64, in <module>
    print '%s does not exist, exiting' % args.feacat
AttributeError: 'Namespace' object has no attribute 'feacat'

**Comment by antoniomo** [comment]
Hi! Two issues there: first a typo (fixed right now) and then you aren't setting the path to `feacat` properly (using the argument `-fc`).

You can find `feacat` in https://github.com/aalto-speech/AaltoASR as part of the `aku` utilities.

**Comment by antoniomo** [comment]
Please note the updated documentation, hope it helps :)

**Comment by shantanudev** [comment]
Thank you!
