### ISSUE TITLE
Dockerfile is missing the step to install ffmpeg

### ISSUE THREAD

**Issue by tran2** [aalto-speech/speaker-diarization#10]
I had to run these extra commands to get ffmpeg (for converting to wav)
```
dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
yum install ffmpeg
```

**Comment by antoniomo** [comment]
Right,

That's technically an extra as the ffmpeg isn't required to compile the dependencies, but of course it's good to have if you plan on passing non-wav files. So perhaps send a pull request with the change and I'll merge it?

Thanks!
