### ISSUE TITLE
DockerHub-hosted image not up to date

### ISSUE THREAD

**Issue by mlovic** [aalto-speech/speaker-diarization#13]
PR #11 added the missing dependency `ffmpeg` to the Dockerfile, but did not deploy a new image to the [DockerHub repo](https://hub.docker.com/r/blabbertabber/aalto-speech-diarizer/) mentioned in the README (blabbertabber/aalto-speech-diarizer). So the latest image in that repo does not incorporate the fix (it's 11 months old).

I'm not sure if the owner of that repo is associated with this project, but it would be great to update the image, or at least update the README with a warning (I'd be happy to do that).

Thanks!

**Comment by antoniomo** [comment]
Hi!

Unfortunately the Dockerfile repo owner isn't related to the project. I think it would be better to let them a few days to answer on #11 so they can maybe update the image, and if they aren't interested anymore maybe there can be a fork or just a warning on the README (and I'll be very happy to accept PRs for that :) )
