### ISSUE TITLE
I want to make a wav file using stdout, how can i make?

### ISSUE THREAD

**Issue by melonicedlatte** [aalto-speech/speaker-diarization#14]
Hello. I'm gohn and your source is very great! 
I use docker and run .sh file and make stdout.

audio=meeting.wav lna=a_1 start-time=0.384 end-time=5.82 speaker=speaker_1
audio=meeting.wav lna=a_2 start-time=5.82 end-time=31.648 speaker=speaker_2
audio=meeting.wav lna=a_3 start-time=31.648 end-time=58.272 speaker=speaker_1
audio=meeting.wav lna=a_4 start-time=60.032 end-time=66.536 speaker=speaker_1
audio=meeting.wav lna=a_5 start-time=66.536 end-time=68.748 speaker=speaker_2
audio=meeting.wav lna=a_6 start-time=68.748 end-time=70.576 speaker=speaker_2
audio=meeting.wav lna=a_7 start-time=70.576 end-time=78.264 speaker=speaker_2
audio=meeting.wav lna=a_8 start-time=79.84 end-time=80.248 speaker=speaker_2
audio=meeting.wav lna=a_9 start-time=80.248 end-time=82.792 speaker=speaker_2
audio=meeting.wav lna=a_10 start-time=82.792 end-time=83.372 speaker=speaker_2
audio=meeting.wav lna=a_11 start-time=83.372 end-time=88.96 speaker=speaker_2
audio=meeting.wav lna=a_12 start-time=88.96 end-time=93.288 speaker=speaker_1
audio=meeting.wav lna=a_13 start-time=93.288 end-time=93.9 speaker=speaker_2
audio=meeting.wav lna=a_14 start-time=93.9 end-time=96.436 speaker=speaker_1
audio=meeting.wav lna=a_15 start-time=96.436 end-time=98.436 speaker=speaker_2
audio=meeting.wav lna=a_16 start-time=98.436 end-time=102.736 speaker=speaker_2
audio=meeting.wav lna=a_17 start-time=102.736 end-time=103.284 speaker=speaker_2
audio=meeting.wav lna=a_18 start-time=103.284 end-time=103.888 speaker=speaker_2

But, i want to make a file that each speaker's speaking file. 
speaker_1/~~~.wav
speaker_2/~~~.wav

Your source have this method or other method to make each wav file?

**Comment by antoniomo** [comment]
Hi!

Glad you like it :)

About your requirement, you want each `.wav` file to have just the audio content of each speaker? That is:

```shell
speaker_1/audio.wav  # A wav file with the concatenation of every speaker_1 part of audio.wav
speaker_2/audio.wav  # A wav file with the concatenation of every speaker_2 part of audio.wav
```

Is this it? In that case, there's no audio post-processing on this package as-is, so it won't do this automatically, but you could write a `python` or `awk` script that takes the output, parses each `start-time=xxx`, `end-time=xxx` and `speaker=xxx` with a regex, and calls `ffmpeg` to cut the appropriate segment of the original `.wav`. You can later join all the `speaker_x` segments together.

This answer is pretty close to what you want, you just need to modify the parsing part to this format: https://unix.stackexchange.com/a/400032/6301

**Comment by melonicedlatte** [comment]
Thank You !!  < ^ o ^ > !!

I use python and now i'm making split file.

But, i meet a new problem. 
I'm a korean, and i test one wav file. 
But, performance is not good.

How can i solve this situation you think??

**Comment by antoniomo** [comment]
Is the audio in Korean? The language model that is included is for English language. It _would_ be possible to train a Korean language model with a lot of annotated data and using https://github.com/aalto-speech/AaltoASR but that's quite a big task and I can't guide you through it :(

**Comment by melonicedlatte** [comment]
Thank you. 👍👍👍 
I will test other korean .wav file.
And I have to see that source and confirm that i can use it.

Thank you for your rapid answer.

**Comment by antoniomo** [comment]
Closing as it seems this was answered :)
