### ISSUE TITLE
Speed is too slow. Is this docker can use gpu?

### ISSUE THREAD

**Issue by melonicedlatte** [aalto-speech/speaker-diarization#15]
Hello. I answer again.
I use your library now, using docker.

But, it is too slow. 
I put my wav file about 250MB, but it use so many cpu resource and it takes more than 2 hours. (Actually, it is still running. So, i don't know when is the finish. )

Can this library using gpu??
How can i made this work fast more than now??

**Comment by antoniomo** [comment]
Hi,

No GPU support out of the box. This repository is in maintenance-mode only (that is, only severe bugs are fixed) but if you want to contribute with a PR, that's welcome :)
