### ISSUE TITLE
Building my own model

### ISSUE THREAD

**Issue by Umar17** [aalto-speech/speaker-diarization#17]
Dear developers,

I want to build my own hmm model based on my own training data. Is training code included there? How can I do that.

Best Regards

**Comment by antoniomo** [comment]
Hi!

The code in this repo doesn't deal with model training.

For training new models, please take a look into: https://github.com/aalto-speech/AaltoASR (in particular the Aku package). You might benefit from looking at https://github.com/aalto-speech/aaltoasr-commands as well, for some extra examples.

Good luck!

**Comment by Umar17** [comment]
Is diarization possible without ASR? Like by just building speakers model?

**Comment by mikkokk** [comment]
Yes, we have current ongoing research on that which is less tied on ASR 
than the old toolkit.

Mikko
