### ISSUE TITLE
Docker Image for Speech Diarization

### ISSUE THREAD

**Issue by cunnie** [aalto-speech/speaker-diarization#3]
@antoniomo :

@saintbrendan and I built a [Docker container](https://hub.docker.com/r/blabbertabber/aalto-speech-diarizer/~/dockerfile/) to host your speech diarizer application to make it easy for people to get up-and-running quickly with the Aalto speaker-diarization software.

**We'd like you to consider incorporating the Dockerfile into the repository, possibly even creating an `aalto-speech` [Docker Hub organization](https://docs.docker.com/docker-hub/orgs/) which has an automated build which builds the Docker container.** In other words, we'd like to give you the Dockerfile and have you maintain it/be responsible for it. Don't misunderstand — we'd be happy to maintain the Dockerfile ourselves; it's just that we don't want to encroach on something that really belongs to you.

Here are some options:

* We could submit a pull-request to place the Dockerfile in the speaker-diarization repo (in `docker/Dockerfile`) and modify the README.md to include instructions to use the Dockerfile.

* We could additionally walk you through the creation of a Docker organization with an automated container build. We could [remote-pair](https://en.wikipedia.org/wiki/Pair_programming) to turbo-charge the process (it should take ~20 minutes).

* Do nothing. My brother and I would continue to happily maintain the Docker container.

Here's how easy it is to diarize a meeting in 4 easy steps with the Docker container (it's much easier than trying to install the python/pip/numpy/scipy, etc...). And it's an especially useful for Windows users.:

```bash
docker run -it blabbertabber/aalto-speech-diarizer bash
cd /speaker-diarization
curl -k -OL https://nono.io/meeting.wav  # sample .wav; substitute yours
./spk-diarization2.py meeting.wav        # substitute your .wav filename
cat stdout                               # browse output
```

**Comment by saintbrendan** [comment]
Ooh, nice email.

**Comment by antoniomo** [comment]
Wow amazing email indeed, thanks!!

I have used docker before so I think option 1 is enough, I can maintain it from them on whenever something changes in the repository, which doesn't happen quite often as I'm no longer actively developing it (other than the occasional bugfix). Of course please keep the authors label on the dockerfile and take full credit for it, and if I were you I would add a "Contributors" section at the end of the README, citing yourselves as contributors of the docker image and maybe add your github handles or email if you feel like.

As for the `aalto-speech` docker hub organization that's not possible for now, as I'm an ex-member of the Aalto University (now I work on industry) and while I can help maintaining this package, I can't take these decisions for them.

Does this make sense? Thanks again!!

**Comment by cunnie** [comment]
Thanks @antoniomo : I have opened [this PR](https://github.com/aalto-speech/speaker-diarization/pull/4) with the changes you suggested and am closing this issue.
