### ISSUE TITLE
Can I recognize only one speaker?

### ISSUE THREAD

**Issue by shadylplplp** [aalto-speech/speaker-diarization#6]
Spk-diarization2.py
You can put a lot of audio in the speaker speak time to identify
Whether he can only identify a specific speaker to improve the accuracy rate
I only need to identify a speaker

Feacat acoustic model config is used to configure this?

Looking forward to your reply
Thank you!

**Comment by antoniomo** [comment]
Hi,

If there's only one speaker in the input audio file, there's nothing special to do, it should identify that speaker's turns assuming the noise conditions stay more or less stable. If that's not enough, what you really want is just speech/non-speech segmentation (also called voice activity detection) and the pretrained models included here are just for typical conditions, if you have something more specific you might want to train your own models for that.

**Comment by antoniomo** [comment]
I'm gonna close this issue for now, let me know if you need something else and we can reopen it :)
