### ISSUE TITLE
Tunable Parameters

### ISSUE THREAD

**Issue by amenegola** [aalto-speech/speaker-diarization#7]
Hello! Awesome repository, thanks for making it available!

I have two questions about parameters used to perform speaker diarization:

The algorithm usually detects 1 speaker when two female speakers are talking on a telephone conversation. Are there any tunable parameters that we could change to get better performance on a specific dataset?

Also, my audios' sample rate is 8kHz. I tried to change fconfig.cfg `sample_rate` parameter to 8000, but the code still throws an exception:

`exception: Audio file sample rate (8000 Hz) and model configuration (16000 Hz) don't agree.`

As an (ugly but really fast) turnaround, I changed every file I found "16000" to "8000", recompiled everything, and then the code runs normally, but I'm not certain if speaker diarization is really working. Which config file should I change sample rate?

Thanks!

**Comment by antoniomo** [comment]
Hi!

Telephone conversations are usually of quite poor quality, however, you can try some things:

- Change the sample rate to 16khz with `sox` to match the models. This doesn't enhance the quality but at least makes it work.
- Also with `sox`, try to reduce the noise:
  - https://superuser.com/questions/588793/need-to-clean-up-audio-noise-using-sox
  - https://gist.github.com/devoncrouse/5534261
  - http://www.zoharbabin.com/how-to-do-noise-reduction-using-ffmpeg-and-sox/
- If the recording conditions are too dominant, probably everything will get clustered into the `speaker_1`. Try making the speaker change detection more sensible, by trying for example a lambda of 0.75:

```
call(['./spk-change-detection.py', vad_recipe, args.feapath,
        '-o', spkchange_recipe, '-m', 'gw', '-d', 'BIC', '-w', '1.0',
        '-st', '3.0', '-dws', '0.1', '-l', '0.75'])  # Lambda to 0.75
```

- Try using GLR with a fine-tuned distance threshold for the spk-clustering2.py:

```
call(['./spk-clustering.py', spkchange_recipe, args.feapath,
          '-o', outfile, '-m', 'hi', '-d', 'GLR', '-t', '3000'])  # Distance: GLR, Threshold: 3000 (fine tune for your data)
```

You'll find that code in the wrapper script `spk-diarization2.py`, make the changes there :)

I hope this helps, let me know to close the issue if possible :)

**Comment by amenegola** [comment]
Hi! Awesome answer, thanks!

I tried to implement the suggestions, they didn't work very well. Sometimes, it really looks like it is working, but it is not most of the time. I understood how changing the lambda and GLR Threshold impacts on segmentation and clustering, but it seems that the problem lies elsewhere. Also, tuning the parameters until I get good results in one audio may not generalize to the rest.

You can close the issue. Thank you very much for the help!

**Comment by antoniomo** [comment]
Sorry I couldn't be of more help! You are totally right, those parameters are data-dependent, so if the recording conditions vary a lot on your dataset, this won't work too well, and you'll need something more advanced than what this package can provide :(

**Comment by antoniomo** [comment]
But of course feel free to open another issue if you can work around that and still want to give this a shot :)
